notifications/urls.py
from django.urls import path
from . import views

app_name = 'notifications'

urlpatterns = [
    path("notification_list/", views.notification_list, name="notification_list"),
    path("notification_mark_read/<int:notification_id>", views.notification_mark_read, name="notification_mark_read"),
    path("notification_delete/<int:notification_id>", views.notification_delete, name="notification_delete"),
    path('notifications/delete-multiple/', views.notification_delete_multiple, name='notification_delete_multiple'),

]

payapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('dashboard/', views.dashboard, name="dashboard"),
]

webapps2024/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='/webapps2024/payapp/', permanent=True)),
    path('webapps2024/register/', include('register.urls')),
    path('webapps2024/transactions/', include('transactions.urls')),
    path('webapps2024/payapp/', include('payapp.urls')),
    path('webapps2024/conversion/', include('conversion.urls')),
    path('webapps2024/notifications/', include(('notifications.urls', 'notifications'), namespace='notifications')),
    path('admin/', admin.site.urls),
    path('favicon.ico', RedirectView.as_view(url='/static/admin/favicon.ico', permanent=True)),
    path('webapps2024/admin/', include('adminapp.urls', 'adminapp')),

]

templates/main/base.html
{% load crispy_forms_tags %}
{% load static %}
{% load mathfilters %}

<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock %}</title>

    <!-- These links will import the Bootstrap CSS and JavaScript files, as well as jQuery and Popper.js -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css"
          integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A=="
          crossorigin="anonymous" referrerpolicy="no-referrer"/>

    <!-- Favicon -->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'logo.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'logo.png' %}">
    <link rel="manifest" href="{% static 'site.webmanifest' %}">
    <link rel="mask-icon" href="{% static 'safari-pinned-tab.svg' %}" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="theme-color" content="#ffffff">

    <link rel="stylesheet" type="text/css" href="{% static '/css/main.css' %}">

</head>


<!--Navbar, bg-light-->
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #7ea1ffa8;">
    <div class="container">
        <a href="#" class="navbar-brand mb-0 mr-3 h1">
            <img alt="logo" src="{% static 'logo.png' %}" width="50" height="50"/>
        </a>
        <!--class="d-inline-block align-top" Add this class after the <img tag. This could be used to align the image to the top-->

        <button
                class="navbar-toggler"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarText"
                aria-controls="navbarText"
                aria-expanded="False"
                aria-label="Toggle navigation"
        >
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-between" id="navbarText">
            <ul class="navbar-nav">
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a href="{% url 'dashboard' %}">Dashboard</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'send&request' %}">Send & Request</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'transactionlog' %}">Activity</a>
                </li>
                {% if user.is_superuser %}
                <li class="nav-item">
                    <a href="{% url 'new_admin_registration' %}">Admin Register</a>
                </li>
                {% endif %}
            </ul>
            <ul>
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a href="{% url 'notifications:notification_list' %}" class="nav-link setting-icon position-relative">
                            <i class="fa-solid fa-bell"></i>
                            <span class="notification-badge">{{ new_notification_count}}</span>
                        </a>
                    </li>
                    <li class="nav-item"><a>Welcome, {{ user.username }}</a></li>
                    <li class="nav-item">
                        <a href="{% url 'logout' %}">Logout</a>
                    </li>
                </ul>
                {% else %}
                <!-- Content for non-authenticated users goes here -->
                {% endif %}
            </ul>
        </div>

    </div>
</nav>

<body>
<div class="container py-5" style="padding-top: 80px;">
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
    {% endif %}

    {% block content %}
    {% endblock %}
</div>

<script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"
></script>
</body>
</html>